/*
 * Copyright (c) 2008, DIaLOGIKa
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of DIaLOGIKa nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY DIaLOGIKa ''AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL DIaLOGIKa BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

using System;
using System.Collections.Generic;
using DIaLOGIKa.b2xtranslator.Spreadsheet.XlsFileFormat.Ptg;

namespace DIaLOGIKa.b2xtranslator.Spreadsheet.XlsFileFormat.DataContainer
{
    public class SharedFormulaData
    {
        /// <summary>
        /// String which stores the index to the sharedstringtable 
        /// </summary>
        private String valueString;

        /// <summary>
        /// Rownumber 
        /// </summary>
        public UInt16 rwFirst;

        /// <summary>
        /// Rownumber 
        /// </summary>
        public UInt16 rwLast;

        /// <summary>
        /// Colnumber 
        /// </summary>
        public UInt16 colFirst;

        /// <summary>
        /// Colnumber 
        /// </summary>
        public UInt16 colLast;

        /// <summary>
        /// Counts the references to this sharedformula
        /// </summary>
        public UInt16 RefCount;

        /// <summary>
        /// The autogenerated ID for this SharedFormula
        /// </summary>
        public int ID; 


        private Stack<AbstractPtg> ptgStack;
        public Stack<AbstractPtg> PtgStack
        {
            get { return this.ptgStack; }
        }

        /// <summary>
        /// This method is used to get the Value from this cell 
        /// </summary>
        /// <returns></returns>
        public string getValue()
        {
            return this.valueString;
        }

        /// <summary>
        /// This method is used to set the value of the cell
        /// </summary>
        /// <param name="obj"></param>
        public void setValue(object obj)
        {
            if (obj is Stack<AbstractPtg>)
            {
                this.ptgStack = (Stack<AbstractPtg>)obj;
            }
        }

        /// <summary>
        /// Checks if the formula cell with this coordinates is in the shared formula range 
        /// </summary>
        /// <param name="rw"></param>
        /// <param name="col"></param>
        public Boolean checkFormulaIsInShared(int rw, int col)
        {
            if ((rw <= this.rwLast) && (rw >= this.rwFirst) &&
                (col <= this.colLast) && (col >= this.colFirst))
                return true;
            else return false; 
        }

        /// <summary>
        /// Converts the classattributes to a string which can be used in the new open xml standard 
        /// This would be: 
        ///     mergeCell ref="B3:C3" 
        ///     ref is  the from the first cell to the last cell 
        /// </summary>
        /// <returns></returns>
        public string getOXMLFormatedData()
        {
            String returnvalue = "";
            returnvalue += ExcelHelperClass.intToABCString(this.colFirst, (this.rwFirst + 1).ToString());
            returnvalue += ":";
            returnvalue += ExcelHelperClass.intToABCString(this.colLast, (this.rwLast + 1).ToString());
            return returnvalue;
        }
    }
}
